-- Generated by `npm run seed` from src/lib/db/seed-data.ts — do not edit by hand.
-- Idempotent: fixed IDs mean re-running updates the same rows.

insert into users (id, name, email, role, department, active) values
  ('11111111-1111-4111-8111-000000000001', 'Joshua', 'joshua@easyeurope.com.my', 'facilitator'::user_role, 'Product', true),
  ('11111111-1111-4111-8111-000000000002', 'May', 'may@easyeurope.com.my', 'manager'::user_role, 'Marketing', true),
  ('11111111-1111-4111-8111-000000000003', 'Esther', 'esther@easyeurope.com.my', 'manager'::user_role, 'Sales', true),
  ('11111111-1111-4111-8111-000000000004', 'Nick', 'nick@easyeurope.com.my', 'manager'::user_role, 'Operations', true),
  ('11111111-1111-4111-8111-000000000005', 'Sue Lyn', 'suelyn@easyeurope.com.my', 'manager'::user_role, 'Procurement', true)
on conflict (id) do update set
  name = excluded.name,
  email = excluded.email,
  role = excluded.role,
  department = excluded.department,
  active = excluded.active;

insert into settings (id, rollout_start_date, tour_window_weeks) values
  (1, '2026-08-10', null)
on conflict (id) do nothing;

insert into metrics (id, name, owner_id, target, direction, unit, definition, live_from_week, sort_order, auto_calc, active) values
  ('22222222-2222-4222-8222-000000000001', 'Total signups', '11111111-1111-4111-8111-000000000005', 50, 'gte'::metric_direction, '', 'New bookings confirmed this week, all departure years.', 1, 1, null, true),
  ('22222222-2222-4222-8222-000000000002', '— of which 2027 departures', '11111111-1111-4111-8111-000000000005', null, 'gte'::metric_direction, '', 'Subset of total signups for 2027 departures.', 1, 2, null, true),
  ('22222222-2222-4222-8222-000000000003', 'New leads', '11111111-1111-4111-8111-000000000002', 330, 'gte'::metric_direction, '', 'New enquiries captured this week, all sources.', 1, 3, null, true),
  ('22222222-2222-4222-8222-000000000004', 'Cost per lead (MTD)', '11111111-1111-4111-8111-000000000002', 12, 'lte'::metric_direction, 'RM', 'Ad spend month-to-date ÷ leads month-to-date.', 2, 4, null, true),
  ('22222222-2222-4222-8222-000000000005', 'Regular % of signups', '11111111-1111-4111-8111-000000000003', 30, 'gte'::metric_direction, '%', 'Repeat customers as a % of this week''s signups.', 3, 5, null, true),
  ('22222222-2222-4222-8222-000000000006', 'Tours Falling Behind', '11111111-1111-4111-8111-000000000003', 0, 'lte'::metric_direction, '', 'Confirmed departures under 15 pax departing within {X} weeks.', 1, 6, null, true),
  ('22222222-2222-4222-8222-000000000007', 'Tours Awaiting Approval', '11111111-1111-4111-8111-000000000003', 0, 'lte'::metric_direction, '', 'Ready on all readiness criteria, awaiting Esther''s sign-off to operate.', 2, 7, null, true),
  ('22222222-2222-4222-8222-000000000008', 'Tours with Critical Issues', '11111111-1111-4111-8111-000000000004', 0, 'lte'::metric_direction, '', 'Open blocker threatening delivery. Threshold to be written (§10 decision 4).', 3, 8, null, true),
  ('22222222-2222-4222-8222-000000000009', 'Tour feedback', '11111111-1111-4111-8111-000000000004', 4, 'gte'::metric_direction, '/5', 'Overall score, most recently completed tour.', 4, 9, null, true),
  ('22222222-2222-4222-8222-000000000010', 'Post-tour report ≤ 7 days', '11111111-1111-4111-8111-000000000004', null, 'yesno'::metric_direction, '', 'Filed on time for tours completed last week.', 4, 10, null, true),
  ('22222222-2222-4222-8222-000000000011', 'To-do completion %', '11111111-1111-4111-8111-000000000001', 90, 'gte'::metric_direction, '%', 'Auto-calculated from the to-do review list. Never entered by hand (R7).', 2, 11, 'todo_completion'::metric_auto_calc, true)
on conflict (id) do update set
  name = excluded.name,
  owner_id = excluded.owner_id,
  target = excluded.target,
  direction = excluded.direction,
  unit = excluded.unit,
  definition = excluded.definition,
  live_from_week = excluded.live_from_week,
  sort_order = excluded.sort_order,
  auto_calc = excluded.auto_calc,
  active = excluded.active;
