/**
 * Seeds the five users and eleven metric definitions.
 *
 *   npm run seed
 *
 * Resets the local dev database to seed state, and regenerates supabase/02-seed.sql from
 * the same source so the two can never drift. The generated SQL is idempotent — IDs are
 * fixed, so re-running it updates rather than duplicating.
 */

import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { DEFAULT_SETTINGS, SEED_METRICS, SEED_USERS } from "../src/lib/db/seed-data";
import { resetLocalStore } from "../src/lib/db/local";

const q = (v: string | null) => (v === null ? "null" : `'${v.replace(/'/g, "''")}'`);
const n = (v: number | null) => (v === null ? "null" : String(v));

function buildSql(): string {
  const users = SEED_USERS.map(
    (u) =>
      `  (${q(u.id)}, ${q(u.name)}, ${q(u.email)}, ${q(u.role)}::user_role, ${q(u.department)}, ${u.active})`,
  ).join(",\n");

  const metrics = SEED_METRICS.map(
    (m) =>
      `  (${q(m.id)}, ${q(m.name)}, ${q(m.owner_id)}, ${n(m.target)}, ${q(m.direction)}::metric_direction, ` +
      `${q(m.unit)}, ${q(m.definition)}, ${m.live_from_week}, ${m.sort_order}, ` +
      `${m.auto_calc === null ? "null" : `${q(m.auto_calc)}::metric_auto_calc`}, ${m.active})`,
  ).join(",\n");

  return `-- Generated by \`npm run seed\` from src/lib/db/seed-data.ts — do not edit by hand.
-- Idempotent: fixed IDs mean re-running updates the same rows.

insert into users (id, name, email, role, department, active) values
${users}
on conflict (id) do update set
  name = excluded.name,
  email = excluded.email,
  role = excluded.role,
  department = excluded.department,
  active = excluded.active;

insert into settings (id, rollout_start_date, tour_window_weeks) values
  (1, ${q(DEFAULT_SETTINGS.rollout_start_date)}, ${n(DEFAULT_SETTINGS.tour_window_weeks)})
on conflict (id) do nothing;

insert into metrics (id, name, owner_id, target, direction, unit, definition, live_from_week, sort_order, auto_calc, active) values
${metrics}
on conflict (id) do update set
  name = excluded.name,
  owner_id = excluded.owner_id,
  target = excluded.target,
  direction = excluded.direction,
  unit = excluded.unit,
  definition = excluded.definition,
  live_from_week = excluded.live_from_week,
  sort_order = excluded.sort_order,
  auto_calc = excluded.auto_calc,
  active = excluded.active;
`;
}

async function main() {
  const sqlPath = join(process.cwd(), "supabase", "02-seed.sql");
  await writeFile(sqlPath, buildSql(), "utf8");
  console.log(`Wrote ${sqlPath}`);

  await resetLocalStore();
  console.log(
    `Reset local dev database: ${SEED_USERS.length} users, ${SEED_METRICS.length} metrics, ` +
      `rollout week 1 starting ${DEFAULT_SETTINGS.rollout_start_date}.`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
